USE [SIC]
GO

CREATE TABLE CARGA_ITRACK (
    IDCARGAPK      INTEGER NOT NULL PRIMARY KEY,
    IDSTATUSPK     INTEGER,
    IDSISTEMAPK    INTEGER,
    DANFE          VARCHAR(44),
    NRONOTAFISCAL  VARCHAR(20),
    DATACRIACAO    DATETIME,
    DESTINATARIO   VARCHAR(20),
    EMBARCADOR     VARCHAR(20),
    TRANSPORTADOR  VARCHAR(20),
    DATA_INSERT    DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE    DATETIME 
);

CREATE INDEX IDX_CARGA_ITRACK_DANFE ON CARGA_ITRACK (DANFE);
