DROP TABLE SIC.dbo.TRB_TMP;
SELECT * INTO SIC.dbo.TRB_TMP FROM (
SELECT TRB.*
FROM SIC.dbo.NOTAFISCAL AS FIS
JOIN CARGASSQL.dbo.TRB ON  TRB.EMP_CODIGO     = SUBSTRING(FIS.DOCUMENTO,1,3) AND
                           TRB.CNH_SERIE      = SUBSTRING(FIS.DOCUMENTO,4,1) AND
     					   TRB.CNH_CTRC       = SUBSTRING(FIS.DOCUMENTO,5,10)
WHERE FIS.MANIFESTO IS NULL
) Z;

UPDATE FIS 
SET FIS.MANIFESTO = CONCAT(TRB.EMP_CODIGO,TRB.MNF_CODIGO)
FROM SIC.dbo.NOTAFISCAL AS FIS
JOIN SIC.dbo.TRB_TMP TRB ON  TRB.EMP_CODIGO     = SUBSTRING(FIS.DOCUMENTO,1,3) AND
                           TRB.CNH_SERIE      = SUBSTRING(FIS.DOCUMENTO,4,1) AND
     					   TRB.CNH_CTRC       = SUBSTRING(FIS.DOCUMENTO,5,10)
WHERE FIS.MANIFESTO IS NULL
;
