-- INSERT INTO SIC.dbo.NOTAFISCAL ( DANFE, DOCUMENTO, CNPJ_EMITENTE, NUMERO , CNPJ_DESTINATARIO,DT_ATUAL )
SELECT -- TOP 10  
	NFR.CHAVENFE                                              as DANFE,
	CONCAT(CNH.EMP_CODIGO,CNH.SERIE,CNH.CTRC)                 as DOCUMENTO,
	SUBSTRING(NFR.CLI_CGCCPF_REMET+CNH.CLI_CGCCPF_REMET,1,14) as CNPJ_EMITENTE,
	RIGHT(REPLICATE('0',7) + CAST(NFR.NF AS VARCHAR),7)       as NUMERO,
	CNH.CLI_CGCCPF_DEST                                       as CNPJ_DESTINATARIO,
	CNH.DATATU                                                as DT_ATUAL
FROM CARGASSQL.dbo.CNH
JOIN CARGASSQL.dbo.NFR ON NFR.EMP_CODIGO = CNH.EMP_CODIGO AND NFR.CNH_CTRC = CNH.CTRC AND NFR.CNH_SERIE = CNH.SERIE
WHERE EXISTS (
SELECT TMP.* 
FROM TEMP_NF_DEST_2021_02_08 TMP
WHERE NOT EXISTS ( SELECT 1 FROM NOTAFISCAL NF
                    WHERE TMP.CNPJ_DESTINATARIO = NF.CNPJ_DESTINATARIO 
				                                 AND TMP.NUMERO = NF.NUMERO )
AND TMP.CNPJ_DESTINATARIO = CNH.CLI_CGCCPF_DEST
AND CAST(TMP.NUMERO AS int ) = NFR.NF
AND NOT EXISTS (SELECT 1 FROM NOTAFISCAL N WHERE N.DANFE = NFR.CHAVENFE )
);




/*
SELECT * FROM NOTAFISCAL NF
WHERE EXISTS (SELECT 1 FROM TEMP_NF_DEST_2021_02_08 TMP WHERE TMP.CNPJ_DESTINATARIO=NF.CNPJ_DESTINATARIO AND TMP.NUMERO = NF.NUMERO)

*/