INSERT INTO SIC.dbo.NOTAFISCAL ( DANFE, DOCUMENTO, CNPJ_EMITENTE, NUMERO , CNPJ_DESTINATARIO,DT_ATUAL )
SELECT   
	TMP.DANFE,
	CONCAT(CNH.EMP_CODIGO,CNH.SERIE,CNH.CTRC)                 as DOCUMENTO,
	CNH.CLI_CGCCPF_REMET as CNPJ_EMITENTE,
	RIGHT(REPLICATE('0',7) + CAST(TMP.NUMERO AS VARCHAR),7)       as NUMERO,
	CNH.CLI_CGCCPF_DEST                                       as CNPJ_DESTINATARIO,
	CNH.DATATU                                                as DT_ATUAL
FROM TEMP_NF_PENDENTE_2021_02_09 TMP
JOIN CARGASSQL.dbo.NFR NF ON NF.CHAVENFE = TMP.DANFE
JOIN CARGASSQL.dbo.CNH    ON NF.EMP_CODIGO = CNH.EMP_CODIGO AND NF.CNH_SERIE = CNH.SERIE AND NF.CNH_CTRC = CNH.CTRC
WHERE CNH.DATATU = (SELECT MAX(CNH2.DATATU) 
                     FROM CARGASSQL.dbo.NFR NF2 
					 JOIN CARGASSQL.dbo.CNH CNH2   ON NF2.EMP_CODIGO = CNH2.EMP_CODIGO AND NF2.CNH_SERIE = CNH2.SERIE AND NF2.CNH_CTRC = CNH2.CTRC
                     WHERE NF2.CHAVENFE = NF.CHAVENFE)
AND NOT EXISTS (SELECT 1 FROM NOTAFISCAL NN WHERE NN.DANFE = TMP.DANFE)
ORDER BY TMP.DANFE


;

UPDATE NF
SET NF.IDCARGA = TMP.IDCARGA,
    NF.DANFE_API = TMP.DANFE
FROM NOTAFISCAL NF
JOIN TEMP_NF_PENDENTE_2021_02_09 TMP ON TMP.DANFE = NF.DANFE
WHERE (NF.IDCARGA = 0 OR NF.IDCARGA IS NULL) 

