USE [SIC]
GO

CREATE TABLE TRACKING (
  ID                INT         NOT NULL    IDENTITY    PRIMARY KEY,
  NRONOTAFISCAL     VARCHAR(20) NOT NULL,
  DANFE             VARCHAR(44) NOT NULL,
  CHAVE             VARCHAR(44),
  CHAVEORIGINAL     VARCHAR(44),
  DT_ATUAL          DATETIME DEFAULT CURRENT_TIMESTAMP,
  ID_OCORRENCIA     INT DEFAULT 0,
  DT_OCORRENCIA     DATETIME,
  DT_SOLUCAO        DATETIME,
  DT_ENVIO          DATETIME,
  OBSERVACAO        VARCHAR(250),
  RET_MENSAGEM      VARCHAR(80),
  RET_PROTOCOLO     VARCHAR(80),
  RET_SUCESSO       INT            DEFAULT 0,
  OUN_TABELA        VARCHAR(20)    NOT NULL,
  OUN_CHAVE         VARCHAR(20)    NOT NULL,
  OUN_DATE          DATETIME       NOT NULL,
  OUN_CODIGO        INT            NOT NULL,
  QTD_REENVIO       INT            DEFAULT 0
);

-- 20/11/2020
ALTER TABLE TRACKING DROP CONSTRAINT DF__TRACKING__IDCARG__6D0D32F4;
ALTER TABLE TRACKING DROP COLUMN IDCARGA;

-- 15/03/2021
CREATE INDEX IDX_TRACKING_DANFE   ON TRACKING (DANFE);
