SELECT FIS.*,CNH.CHAVECTEORIGEM,'1' AS TIPOIMAGEM,
       CLI.LOGIN,CLI.SENHA,CLI.SERVIDOR,CLI.URL_EVIDENCIAR_OCORRENCIA
FROM NOTAFISCAL AS FIS
JOIN CARGASSQL.dbo.CNH    ON CNH.EMP_CODIGO = SUBSTRING(FIS.DOCUMENTO,1,3)       AND 
						     CNH.SERIE      = SUBSTRING(FIS.DOCUMENTO,4,1)       AND 
		                     CNH.CTRC       = SUBSTRING(FIS.DOCUMENTO,5,10)
JOIN SIC.dbo.CLIENTES CLI ON CLI.CNPJ_CLI   = SUBSTRING(CNH.CLI_CGCCPF_PAG,1,8)  OR 
						     CLI.CNPJ_CLI   = SUBSTRING(CNH.CLI_CGCCPF_DEST,1,8) OR
							 CLI.CNPJ_CLI   = SUBSTRING(CNH.CLI_CGCCPF_REMET,1,8)
WHERE FIS.COMPROVANTE_ENVIADO = 0