SELECT EMP.CGC CNPJ_USER,TKN.VALIDO,TKN.TOKEN,FIS.*
FROM SIC.dbo.NOTAFISCAL AS FIS
JOIN CARGASSQL.dbo.EMP on EMP.CODIGO = substring(FIS.DOCUMENTO,1,3)
JOIN SIC.dbo.TOKEN_ITRACK TKN on TKN.CNPJ = EMP.CGC
WHERE TKN.VALIDO <> 0
