SELECT
    CNH.DATACHEGADA  AS DATAINICIOENTREGA,
	CNH.DATACHEGADA  AS DATAFINALIZACAO,
	NFR.DATA         AS DATAEMISSAODANFE,
	NFR.CHAVENFE     AS DANFE,
	CNH.CTRC         AS NROCTE,
	'RESPONSÁVEL NA ENTREGA' AS NOMERECEBEDOR,
	'N.INFO'         AS DOCUMENTORECEBEDOR,
	VEI.TIPO         AS TIPOVEICULO,
	ISNULL(MOT.NOME,'TERMACO') AS MOTORISTA,
	CNH.VEI_PLACA_COL  AS PLACAVEICULO,
    FIS.DOCUMENTO      AS DOCUMENTO,     
    FIS.IDCARGA        AS IDCARGA,
	EMP.CGC CNPJ_USER,TKN.VALIDO,TKN.TOKEN
FROM CARGASSQL.dbo.NFR
JOIN SIC.dbo.NOTAFISCAL FIS ON FIS.DANFE = NFR.CHAVENFE
JOIN CARGASSQL.dbo.CNH ON CNH.EMP_CODIGO = NFR.EMP_CODIGO AND CNH.SERIE = NFR.CNH_SERIE AND CNH.CTRC = NFR.CNH_CTRC
JOIN CARGASSQL.dbo.VEI ON VEI.PLACA = CNH.VEI_PLACA_COL
LEFT JOIN CARGASSQL.dbo.MOT ON MOT.PRONTUARIO = CNH.MOT_PRONTUARIO
JOIN CARGASSQL.dbo.EMP on EMP.CODIGO = substring(FIS.DOCUMENTO,1,3)
JOIN SIC.dbo.TOKEN_ITRACK TKN on TKN.CNPJ = EMP.CGC
WHERE FIS.DANFE = '${danfe}'
  AND FIS.COMPROVANTE_ENVIADO = 0
  AND CNH.DATAENTREGA IS NOT NULL
  AND EXISTS  (select 1 from TRACKING trk  where TRK.DANFE = FIS.DANFE AND TRK.ID_OCORRENCIA=1)

