SELECT FIS.DANFE,FIS.DOCUMENTO,
       CONCAT(TRB.EMP_CODIGO,TRB.MNF_CODIGO) AS MANIFESTO,
       TRB.DATA AS DT_MANIFESTO,
       EMP.CGC CNPJ_USER,TKN.VALIDO,TKN.TOKEN
FROM SIC.dbo.NOTAFISCAL FIS
JOIN CARGASSQL.dbo.TRB ON  TRB.EMP_CODIGO     = SUBSTRING(FIS.DOCUMENTO,1,3) AND
                           TRB.CNH_SERIE      = SUBSTRING(FIS.DOCUMENTO,4,1) AND
     					   TRB.CNH_CTRC       = SUBSTRING(FIS.DOCUMENTO,5,10)
JOIN CARGASSQL.dbo.EMP on EMP.CODIGO = substring(FIS.DOCUMENTO,1,3)
JOIN SIC.dbo.TOKEN_ITRACK TKN on TKN.CNPJ = EMP.CGC
WHERE FIS.MANIFESTO IS NULL
  AND TKN.VALIDO <> 0


