SELECT FIS.*,FIS.CNPJ_TRANSPORTADOR CNPJ_USER,TKN.VALIDO,TKN.TOKEN 
FROM SIC.dbo.NOTAFISCAL FIS
JOIN SIC.dbo.TOKEN_ITRACK TKN on TKN.CNPJ = FIS.CNPJ_TRANSPORTADOR
WHERE FIS.IDCARGA = 0 
  AND ( FIS.DT_VALIDACAO IS NULL OR DATEDIFF(minute,FIS.DT_VALIDACAO, CURRENT_TIMESTAMP) > 30)
  AND TKN.VALIDO <> 0     
  AND FIS.DANFE IS NOT NULL
  AND LEN(FIS.DANFE) > 0
  AND ( FIS.DT_VALIDACAO IS NULL OR DATEDIFF(day,FIS.DT_ATUAL, CURRENT_TIMESTAMP) < 35)