SELECT FIS.*,FIS.CNPJ_TRANSPORTADOR CNPJ_USER,TKN.VALIDO,TKN.TOKEN 
FROM SIC.dbo.NOTAFISCAL FIS
JOIN SIC.dbo.TOKEN_ITRACK TKN on TKN.CNPJ = FIS.CNPJ_TRANSPORTADOR
WHERE FIS.IDCARGA = 0 
  AND ( FIS.DT_UPDATE IS NULL OR DATEDIFF(minute,FIS.DT_UPDATE, CURRENT_TIMESTAMP) > 40) -- UPDATE MAIOR QUE 40 MINUTOS
  AND TKN.VALIDO <> 0     
  AND FIS.DANFE IS NOT NULL
  AND LEN(FIS.DANFE) > 0
  AND ( FIS.DT_VALIDACAO IS NULL OR DATEDIFF(day,FIS.DT_ATUAL, CURRENT_TIMESTAMP) < 35)     --- NF NÃO TER MAIS DE 35 DIAS
  AND ( FIS.DT_VALIDACAO IS NULL OR DATEDIFF(day,FIS.DT_VALIDACAO, CURRENT_TIMESTAMP) < 3)  --- VALIDAÇÃO NÃO TER 3 DIAS