SELECT TOP 200 TRK.*,FIS.IDCARGA,EMP.CGC CNPJ_USER,TKN.VALIDO,TKN.TOKEN  
FROM SIC.dbo.TRACKING TRK
JOIN SIC.dbo.NOTAFISCAL FIS ON FIS.DANFE = TRK.DANFE
JOIN CARGASSQL.dbo.EMP on EMP.CODIGO = substring(FIS.DOCUMENTO,1,3)
JOIN SIC.dbo.TOKEN_ITRACK TKN on TKN.CNPJ = EMP.CGC
WHERE TRK.RET_SUCESSO = 0 
  AND FIS.IDCARGA > 0
  AND FIS.COMPROVANTE_ENVIADO = 0 --- Comprovante ainda não enviado
  AND ( TRK.DT_ENVIO IS NULL OR DATEDIFF(minute,TRK.DT_ENVIO, CURRENT_TIMESTAMP) > 30)   --- depois de 30min da ultima tentativa
  AND ( TRK.DT_ENVIO IS NULL OR DATEDIFF(day,TRK.DT_ENVIO, CURRENT_TIMESTAMP) < 3 )      --- ATE 3 DIAS
  AND TKN.VALIDO <> 0
  AND (CASE WHEN SUBSTRING(TRK.RET_MENSAGEM,1,4)='Erro' AND TRK.QTD_REENVIO>20 THEN 0 ELSE 1 END) = 1 -- repete até 20 tentativas com erro
ORDER BY TRK.QTD_REENVIO,TRK.DANFE,TRK.DT_OCORRENCIA