SELECT TOP 2 TRK.*,FIS.IDCARGA  
FROM TRACKING TRK
JOIN NOTAFISCAL FIS ON FIS.DANFE = TRK.DANFE
WHERE TRK.RET_SUCESSO = 0 AND  
      FIS.IDCARGA > 0 AND
      ( TRK.DT_ENVIO IS NULL OR DATEDIFF(minute,TRK.DT_ENVIO, CURRENT_TIMESTAMP) > 30)
ORDER BY TRK.DANFE,TRK.DT_OCORRENCIA