SELECT TOP 500 TRK.*,FIS.IDCARGA,EMP.CGC CNPJ_USER,TKN.VALIDO,TKN.TOKEN  
FROM SIC.dbo.TRACKING TRK
JOIN SIC.dbo.NOTAFISCAL FIS ON FIS.DANFE = TRK.DANFE
JOIN CARGASSQL.dbo.EMP on EMP.CODIGO = substring(FIS.DOCUMENTO,1,3)
JOIN SIC.dbo.TOKEN_ITRACK TKN on TKN.CNPJ = EMP.CGC
WHERE TRK.RET_SUCESSO = 0 
  AND FIS.IDCARGA > 0 
  AND ( TRK.DT_ENVIO IS NULL OR DATEDIFF(minute,TRK.DT_ENVIO, CURRENT_TIMESTAMP) > 30)
  AND TKN.VALIDO <> 0
ORDER BY TRK.DANFE,TRK.DT_OCORRENCIA