INSERT INTO TRACKING 
      (NRONOTAFISCAL,DANFE,DT_ATUAL,DT_OCORRENCIA,ID_OCORRENCIA,OBSERVACAO,RET_SUCESSO,OUN_TABELA,OUN_CHAVE,OUN_DATE,OUN_CODIGO )
SELECT 
      FIS.NUMERO,FIS.DANFE,CURRENT_TIMESTAMP,MNF.EMBARQUE,302,'SAIDA NO CENTRO DE DISTRIBUICAO (CDOUT)',
	  0,'MNF',CONCAT(TRB.EMP_CODIGO,TRB.MNF_CODIGO),CURRENT_TIMESTAMP,302
FROM NOTAFISCAL FIS
JOIN CARGASSQL.dbo.TRB ON  TRB.EMP_CODIGO     = SUBSTRING(FIS.DOCUMENTO,1,3) AND
                           TRB.CNH_SERIE      = SUBSTRING(FIS.DOCUMENTO,4,1) AND
     					   TRB.CNH_CTRC       = SUBSTRING(FIS.DOCUMENTO,5,10)
JOIN CARGASSQL.dbo.MNF ON  MNF.EMP_CODIGO     = TRB.EMP_CODIGO AND
                           MNF.CODIGO         = TRB.MNF_CODIGO
LEFT JOIN TRACKING TRK ON  TRK.DANFE          = FIS.DANFE AND
                           TRK.ID_OCORRENCIA  = 302
WHERE FIS.MANIFESTO IS NOT NULL AND FIS.DT_MANIFESTO IS NULL AND TRK.DANFE IS NULL
