INSERT INTO TRACKING 
      (NRONOTAFISCAL,DANFE,DT_ATUAL,DT_OCORRENCIA,ID_OCORRENCIA,OBSERVACAO,RET_SUCESSO,OUN_TABELA,OUN_CHAVE,OUN_DATE,OUN_CODIGO )
SELECT
      FIS.NUMERO,FIS.DANFE,CURRENT_TIMESTAMP,OUN.DATAOCO,OUN.OCO_CODIGO,SUBSTRING(OUN.DESCRICAO,1,250),
	  0,OUN.TABELA,OUN.CHAVE,OUN.DATA,OUN.OCO_CODIGO
FROM CARGASSQL.dbo.OUN
    JOIN NOTAFISCAL  FIS                 ON FIS.DOCUMENTO      = OUN.CHAVE
	JOIN CARGASSQL.dbo.CNH               ON CNH.EMP_CODIGO     = SUBSTRING(OUN.CHAVE,1,3)          AND 
											CNH.SERIE          = SUBSTRING(OUN.CHAVE,4,1)          AND 
											CNH.CTRC           = SUBSTRING(OUN.CHAVE,5,10)
	JOIN SIC.dbo.CLIENTES CLI            ON CLI.CNPJ_CLI       = SUBSTRING(CNH.CLI_CGCCPF_PAG,1,8)  OR 
											CLI.CNPJ_CLI       = SUBSTRING(CNH.CLI_CGCCPF_DEST,1,8) OR
											CLI.CNPJ_CLI       = SUBSTRING(CNH.CLI_CGCCPF_REMET,1,8)
	LEFT JOIN SIC.dbo.TRACKING TRK       ON TRK.OUN_TABELA     = OUN.TABELA AND
	                                        TRK.OUN_CHAVE      = OUN.CHAVE  AND
											TRK.OUN_DATE       = OUN.DATA
    JOIN SIC.dbo.DE_PARA_OCORRENCIAS DPA ON DPA.CARGAS_ID = OUN.OCO_CODIGO
WHERE 
    OUN.TABELA='CNH' AND  TRK.OUN_CODIGO IS NULL 
