INSERT INTO TRACKING (NRONOTAFISCAL,DANFE,ID_OCORRENCIA,DT_OCORRENCIA,OBSERVACAO,RET_SUCESSO,OUN_TABELA,OUN_CHAVE,OUN_DATE,OUN_CODIGO)
SELECT   
  NFE.NUMERO AS NRONOTAFISCAL,
  NFE.DANFE  AS DANFE,
  0          AS ID_OCORRENCIA,
  CURRENT_TIMESTAMP AS DT_OCORRENCIA,
  'PROCESSO DE TRANSPORTE INICIADO' AS OBSERVACAO,
  0      AS RET_SUCESSO,
  'NFR'  AS OUN_TABELA,
  'INIT' AS OUN_CHAVE,
  CURRENT_TIMESTAMP AS OUN_DATE,
  0      AS OUN_CODIGO
 FROM NOTAFISCAL NFE
 LEFT JOIN TRACKING TRK ON TRK.DANFE = NFE.DANFE
 WHERE TRK.OUN_CODIGO IS NULL