UPDATE NF 
SET NF.IDCARGA      = IT.IDCARGAPK,
    NF.DT_VALIDACAO = CURRENT_TIMESTAMP,
	NF.DANFE        = IT.DANFE
FROM NOTAFISCAL NF
JOIN CARGA_ITRACK IT ON IT.DANFE = NF.DANFE
WHERE NF.IDCARGA = 0

