UPDATE FIS
SET FIS.DT_BAIXA_MANIFESTO = CURRENT_TIMESTAMP
FROM NOTAFISCAL FIS
JOIN TRACKING TRK ON  TRK.DANFE         = FIS.DANFE AND
                      TRK.ID_OCORRENCIA = 98
WHERE FIS.DT_BAIXA_MANIFESTO IS NULL 
