-- ANTES RODAR CREATE (SELECT * FROM CARGA_ITRACK_TMP)
UPDATE NF 
SET NF.IDCARGA      = IT.IDCARGAPK,
    NF.DT_VALIDACAO = CURRENT_TIMESTAMP,
	NF.DANFE        = IT.DANFE
FROM NOTAFISCAL NF
JOIN CARGA_ITRACK_TMP IT ON IT.DANFE = NF.DANFE
WHERE NF.IDCARGA = 0

