UPDATE FIS 
SET FIS.MANIFESTO = CONCAT(TRB.EMP_CODIGO,TRB.MNF_CODIGO)
FROM NOTAFISCAL AS FIS
JOIN CARGASSQL.dbo.TRB ON  TRB.EMP_CODIGO     = SUBSTRING(FIS.DOCUMENTO,1,3) AND
                           TRB.CNH_SERIE      = SUBSTRING(FIS.DOCUMENTO,4,1) AND
     					   TRB.CNH_CTRC       = SUBSTRING(FIS.DOCUMENTO,5,10)
WHERE FIS.MANIFESTO IS NULL
